"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.academicYearSchema = exports.universitySchema = exports.studentSchema = exports.statusValueSchema = exports.enrollSchema = exports.enrollLectureSchema = exports.doctorSchema = exports.lectureSchema = exports.courseWithLecturesSchema = exports.courseSchema = exports.studentLoginResponseSchema = exports.studentLoginRequestSchema = exports.jwtPayloadSchema = exports.doctorLoginResponseSchema = exports.doctorLoginSchema = void 0;
const auth_1 = require("./types/auth");
Object.defineProperty(exports, "doctorLoginSchema", { enumerable: true, get: function () { return auth_1.doctorLoginSchema; } });
Object.defineProperty(exports, "doctorLoginResponseSchema", { enumerable: true, get: function () { return auth_1.doctorLoginResponseSchema; } });
Object.defineProperty(exports, "jwtPayloadSchema", { enumerable: true, get: function () { return auth_1.jwtPayloadSchema; } });
Object.defineProperty(exports, "studentLoginRequestSchema", { enumerable: true, get: function () { return auth_1.studentLoginRequestSchema; } });
Object.defineProperty(exports, "studentLoginResponseSchema", { enumerable: true, get: function () { return auth_1.studentLoginResponseSchema; } });
const course_1 = require("./types/course");
Object.defineProperty(exports, "courseSchema", { enumerable: true, get: function () { return course_1.courseSchema; } });
Object.defineProperty(exports, "courseWithLecturesSchema", { enumerable: true, get: function () { return course_1.courseWithLecturesSchema; } });
Object.defineProperty(exports, "lectureSchema", { enumerable: true, get: function () { return course_1.lectureSchema; } });
const doctor_1 = require("./types/doctor");
Object.defineProperty(exports, "doctorSchema", { enumerable: true, get: function () { return doctor_1.doctorSchema; } });
const enrolment_1 = require("./types/enrolment");
Object.defineProperty(exports, "enrollLectureSchema", { enumerable: true, get: function () { return enrolment_1.enrollLectureSchema; } });
Object.defineProperty(exports, "enrollSchema", { enumerable: true, get: function () { return enrolment_1.enrollSchema; } });
const student_1 = require("./types/student");
Object.defineProperty(exports, "statusValueSchema", { enumerable: true, get: function () { return student_1.statusValueSchema; } });
Object.defineProperty(exports, "studentSchema", { enumerable: true, get: function () { return student_1.studentSchema; } });
const university_1 = require("./types/university");
Object.defineProperty(exports, "universitySchema", { enumerable: true, get: function () { return university_1.universitySchema; } });
const academicYear_1 = require("./types/academicYear");
Object.defineProperty(exports, "academicYearSchema", { enumerable: true, get: function () { return academicYear_1.academicYearSchema; } });
